### ISSUE TITLE
Python 3 issues

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/acme_diags#153]
When converting to Python 3, the following issues are present:

- [ ] There's a `b'` on each webpage. Including those without the header.
![screen shot 2018-04-23 at 2 49 24 pm](https://user-images.githubusercontent.com/4239938/39155184-d40d1cd0-4705-11e8-9be4-49ead75518b9.png)
![screen shot 2018-04-23 at 2 48 47 pm](https://user-images.githubusercontent.com/4239938/39155187-d5b96f52-4705-11e8-8522-ed9929dd7fe4.png)
- [x] The output metadata has `\` before every `'`. We don't want this.
![screen shot 2018-04-23 at 2 52 21 pm](https://user-images.githubusercontent.com/4239938/39155246-10bf8654-4706-11e8-80a6-531d9b406a16.png)

**Comment by zshaheen** [comment]
- [ ] We also need to release a new version of the `output_viewer` with the bugfix.

**Comment by doutriaux1** [comment]
it's a python3 thing with strings being bytes. You'll need to do something along these line:
```python
        read = P.stdout.readline().rstrip()
        out.append(str(read))
```

**Comment by zshaheen** [comment]
@doutriaux1 Ahhh, thanks for the hint! It must be that for sure. Now I just need to find where in `output_viewer` to fix it.
