### ISSUE TITLE
too many opened figures with matplotlib

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/acme_diags#154]
got these warning while running the software:
```
/export_2/zhang40/anaconda2/envs/acme_diags_env_130/lib/python2.7/site-packages/matplotlib/pyplot.py:524: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
```

**Comment by zshaheen** [comment]
@muryanto1 Just reported that she also has these issues when running the nightly Jenkins test suite. This was with 24 processes. This warning caused the entire run to stop and die.

**Comment by xylar** [comment]
@zshaheen and @chengzhuzhang, we ran into this issue in MPAS-Analysis.  We found it was easily solved by just closing each plot after saving it.  This is appropriate if you typically run matplotlib in "headless" mode, in which case you should just be able to do something like:
```python
if fileout is not None:
    plt.savefig(fileout, dpi=dpi, bbox_inches='tight', pad_inches=0.1)

if not displayToScreen:
    plt.close()
```
That's what we do in MPAS-Analysis.  At this point, we don't ever run with `displayToScreen=True` but had found such an option to be useful in the early stages of debugging our plots.

Maybe you've got this fully under control and don't need any input from me...

**Comment by chengzhuzhang** [comment]
@xylar Thank you very much for sharing the experience! We will definitely give it a try to fix this issue. On the other hand, there might be some deeper memory issue we have to investigate in the package, since this warning occur after v1.3.x...

**Comment by xylar** [comment]
@chengzhuzhang, my guess would be that v1.3.x maybe just opens more plots (without closing them) than previous versions did.  matplotlib really does start complaining at a pretty small number of figures (well under 100 if memory serves) so it's best to get in the habit of either reusing or closing figures in my experience.  I don't think there's any relationship between this error and using memory elsewhere, it's just sort of a self-imposed limit on number of figures internal to matplotlib.

**Comment by zshaheen** [comment]
Done in 19be26a918f5e45bfee0f409c534f7b99335a505. Thanks @xylar for the help! :)
