### ISSUE TITLE
mesalib included as a dependency

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/acme_diags#157]
@zshaheen and @doutriaux1,

It looks like you have included `mesalib` as a dependency of `acme_diags`:
https://github.com/E3SM-Project/acme_diags/blob/master/conda/meta.yaml#L26

The only way for me to create a version of `e3sm-unified` that includes x-windows support is to leave out `mesalib` as a dependency, which I cannot do if include the latest `acme_diags`.  So a few questions for you both:
1. Does `acme_diags` work without `mesalib`?
  a. If so, is the desired default installation of `acme_diags` the one without x-windows support?
  b. If yes to both of these, is there any way of having this be the default but explicitly specifying that we want to exclude mesalib in an install with x-windows support?
2. If not, presumably there is so reason to try supporting the x-windows version of `cdat` under `e3sm-unified`, since I cannot build a version that supports x-windows, right?
3. Who (if anyone) currently uses `cdat`'s x-windows capabilities under `e3sm-unified`?

**Comment by zshaheen** [comment]
@xylar @doutriaux1 I'll remove this as a dependency, it'll make it easier for everyone. I hope to release another version this week with that.

Thanks again @xylar for doing all the stuff related to the unified env!

**Comment by xylar** [comment]
Thanks @zshaheen.  I appreciate you accommodating the broader needs of the project.

**Comment by zshaheen** [comment]
@xylar All of these issues were fixed in `v1.3.3` of `e3sm_diags`. I sent you an email regarding this. Also, the package name now `e3sm_diags`, and not `acme_diags`.

Feel free to reopen this issue if there are problems.

**Comment by xylar** [comment]
Thanks, @zshaheen.  I can confirm that I can now make e3sm-unified environments with x-windows support.
