### ISSUE TITLE
Wrong permissions for obs files

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/acme_diags#160]
@chengzhuzhang , some of the observational file permissions are not set correctly on edison:/global/project/projectdirs/acme/acme_diags/obs_for_acme_diags

For example,
-rwxr-x--- 1 chengzhu chengzhu    263088 Apr 10 15:23 CRU_ANN_climo.nc

gives the errors:
CDMS system error: Permission denied
CDMS I/O error: Opening file /global/project/projectdirs/acme/acme_diags/obs_for_acme_diags/CRU_ANN_climo.nc
Error in acme_diags.driver.lat_lon_driver

**Comment by chengzhuzhang** [comment]
@tangq  The permission is now fixed. sorry about the inconvenience. we are looking into issue #161 now...
