### ISSUE TITLE
Individual Figures

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/acme_diags#167]
Is there a way in E3SM-Diags to have the individual subplots printed out individually for the comparison plots?  For example, a typical output figure has three panels, 1)  Model, 2) Observed, 3) Difference.  I always want to take a few of these figures and include them in presentations or papers, but not necessarily in the same template as the standard output.  I end up making three copies and then cropping out the individual pieces myself, but if it is possible to get all three figures individually that would be awesome and save me a lot of time.

**Comment by golaz** [comment]
@AaronDonahue : unfortunately this is currently not supported. But I agree with you that it would be very useful. I often end-up having to crop to extract individual panels.

I'm trying to think how best we could implement this feature:
1.  Add an option to additionally save individual panel plots in separate files. Relatively simple to implement, but somewhat wasteful because we would generate plots multiple times.
2.  Always save as separate plot files. Cleaner, but it would break the html viewer (which is not that easy to fix since the person who wrote it is no longer here).

Any suggestions on how you would like to see it implemented?

**Comment by golaz** [comment]
Maybe this would be the most elegant solution:

https://stackoverflow.com/questions/4325733/save-a-subplot-in-matplotlib

**Comment by PeterCaldwell** [comment]
This is somewhat of an aside, but I've been using pieces of the underlying e3sm_diags code lately to generate graphics I want. I can create and save individual panels that way, but the figsize dimension is used in a hardcoded way which can't easily be changed (so I still end up cropping white space from my 1-panel plot).

**Comment by golaz** [comment]
Yes, I made the decision earlier on to hard code figure sizes and subplots location. It's not ideal, but it was the best solution I could find to guarantee that each panels would always be **exactly** at the same location on every single plot. I didn't like the AMWG feature in which subplots change size and location depending things like the length of the experiment name.

**Comment by PeterCaldwell** [comment]
Roger that. Having extra white space is a small price to pay for not having figures overwriting each other and doing strange things.

**Comment by golaz** [comment]
@AaronDonahue, new feature to save individual panel plots has been implemented in PR https://github.com/E3SM-Project/acme_diags/pull/169.

Waiting on @zshaheen to check code and merge to master.

**Comment by zshaheen** [comment]
Everything looks great, Chris' additions are now in master. As Chris stated, the [PR](https://github.com/E3SM-Project/acme_diags/pull/169) explains how to use the new parameter.

To create an env to use the latest code on master, please read [this](https://e3sm-project.github.io/acme_diags/docs/html/install.html#environment-for-development).

**Comment by AaronDonahue** [comment]
@zshaheen and @golaz , awesome thanks!  I'll check it out.

**Comment by zshaheen** [comment]
If there are any issues, please feel free to open this issue again.
