### ISSUE TITLE
File permissions on Rhea

### ISSUE THREAD

**Issue by crjones-amath** [E3SM-Project/acme_diags#172]
I have followed the very clear and helpful steps up through (7a) in the [Quick Guide for Rhea](https://e3sm-project.github.io/acme_diags/docs/html/quick-guide-rhea.html) documentation.

I'm trying a test run with the suggested test dataset, but get a whole slew of CDMS errors, which I assume file permission issues? E.g., 

> CDMSError: Cannot open file /ccs/proj/cli115/acme_diags_data/test_model_data_for_acme_diags/20161118.beta0.FC5COSP.ne30_ne30.edison_ANN_climo.nc (No error)
> Starting to run E3SM Diagnostics.
> test file: /ccs/proj/cli115/acme_diags_data/test_model_data_for_acme_diags/20161118.beta0.FC5COSP.ne30_ne30.edison_DJF_climo.nc
> reference file: /ccs/proj/cli115/acme_diags_data/obs_for_acme_diags/ceres_ebaf_surface_v4.0_DJF_200101_201512_climo.nc
> CDMS system error: Permission denied
> CDMS I/O error: Opening file /ccs/proj/cli115/acme_diags_data/test_model_data_for_acme_diags/20161118.beta0.FC5COSP.ne30_ne30.edison_DJF_climo.nc
> Error in acme_diags.driver.zonal_mean_xy_driver

Here's the error I get when I try to look at one of the files with ncks:

> ERROR User does not have read permission for /ccs/proj/cli115/acme_diags_data/test_model_data_for_acme_diags/20161118.beta0.FC5COSP.ne30_ne30.edison_ANN_climo.nc, or file does not exist

**Comment by chengzhuzhang** [comment]
@crjones-amath I just changed the group for test data. Would you please try again and let me know? Thank you for trying it on Rhea!

**Comment by crjones-amath** [comment]
@chengzhuzhang Thanks! That did the trick.
