### ISSUE TITLE
Showing both test and reference full model name in viewer?

### ISSUE THREAD

**Issue by kaabre** [E3SM-Project/acme_diags#185]
![image](https://user-images.githubusercontent.com/21698499/46983874-53d66a00-d097-11e8-9034-e23c0290fc12.png)

The viewer page only has a spot to show the test model name, not the reference name as well.  In model_vs_model I would like it to show both.  I had made some modifications to accomplish this, but I didn't keep them up through subsequent code changes.

What I had done:
![image](https://user-images.githubusercontent.com/21698499/46983974-d2330c00-d097-11e8-9fef-b174b3d9b878.png)

It would be nice if the official program could do something like this (preferably in a nicer-looking way).  Currently, if I offer a 'short' reference_name, the original reference model name does not appear anywhere in the plots or the viewer webpages (although it does appear in the provenance, at least, so it isn't completely lost)

**Comment by kaabre** [comment]
(I'm going to just be trying to get that developer-environment fix back to work, but wanted to make an issue on this so it was on your radar)

**Comment by zshaheen** [comment]
@kaabre Here's what changes in 9b83bda54c806e526d9fcf64dd070a94582b5f6a result in. Please click on the images to see them clearly.

* **Model vs Model**
![screen shot 2018-10-16 at 1 24 42 pm](https://user-images.githubusercontent.com/4239938/47045538-e7677380-d147-11e8-8c16-34210860abef.png)


* **Model vs Obs**
![screen shot 2018-10-16 at 1 24 50 pm](https://user-images.githubusercontent.com/4239938/47045531-e5051980-d147-11e8-8088-0476630762a1.png)

**Comment by zshaheen** [comment]
@kaabre, I'm guessing you're fine with everything as is. Let us know if you want more changes or if you have new ideas. Thanks again for the input 😄
