### ISSUE TITLE
When Edison is gone, will diagnostics works in the same way on cori?

### ISSUE THREAD

**Issue by oksanaguba** [E3SM-Project/acme_diags#193]
Creating an issue cause i don't know where to post this question.

**Comment by oksanaguba** [comment]
apparently the previous issue is for cori, closing this then.

**Comment by zshaheen** [comment]
I'm currently testing on Cori and there seems to be some small issues with syntax. It shouldn't be too bad. When this is working, we'll have a quick start guide for Cori as well.

**Comment by oksanaguba** [comment]
Thanks!
