### ISSUE TITLE
Add quality control to user input

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/acme_diags#37]
Check that all needed keywords are present.
The ACMEParameters class already does this, but if the user spells "sets" as "set" still doesn't give an error.

**Comment by chengzhuzhang** [comment]
Another example is if the user wants a zonal mean xy plot but fill in a 3d variable without specifying the pressure level. should have warning/error message for this kind of behavior too.

**Comment by zshaheen** [comment]
Everything is good.
