### ISSUE TITLE
Change degrees used for the latitude in VCS

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/acme_diags#69]
- [ ] Use 90S, 60S, 30S, 0, 30N, 60N, 90N instead of 90S, 80S, 60S, 40S, 20S, Eq, 20N, 40N, 60N, 80N, 90N.
- [ ] Include the degree symbol 

Needed for:
- [ ] zonal mean xy
- [ ] zonal mean 2d
- [ ] lat-lon
- [ ] polar

**Comment by doutriaux1** [comment]
@zshaheen you can control tickmarks via the gms
```python
import vcs
gm = x.createisofill()
gm.yticlabels1 = {-90:"90S",-60:"60S",-30:"30S",0:"0",30:"30N",60:"60N",90:"90N"}
```

Or are you talking about the defaults

**Comment by zshaheen** [comment]
Done in f52fdb7fd24c5489e07535bbddfd4750ce4186b4.
